name: Linux

on:
  workflow_dispatch: # for manual workflow trigger
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  linux_cpp14:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: check compiler toos version
        run: |
          gcc --version
          g++ --version
          cmake --version

      - name: build
        run: |
          ls -l
          cat CMakeLists.txt && cmake -B./build
          cd build && cmake --build .

      - name: test
        run: cd build && ctest --output-on-failure
